### ISSUE TITLE
R&D Icons

### ISSUE THREAD

**Issue by ChrisViral** [StupidChris/KSPX#2]
Given the new TechTree is now open to moddability through ModuleManager, I thought including new icons for KSPX would be a good idea. While most parts do fit in nicely, at least two stand out and would likely require a new node each: the LV-NB (2.5m Nuclear Engine), and the PB-ION2 (the 1.25m Ion Engine). Bumping both of those to nodes one step further from thewir smaller counterparts would be pretty nice, but reusing existing stock icons would probably be pretty lame. So I was thinking my pal @sumghai could help me here :)

The icons need to be 32x32 .png images, white on transparent background with slight airbrushing for shadows and relief. I reccomend you base yourself off from the "R&D_node_icon_ionpropulsion" and "R&D_node_icon_nuclearpropulsion" icons to build off the two new.

That of course is if you can do this :)

**Comment by sumghai** [comment]
I'll have a look at the existing icons right away, and see what I can do.

**Comment by sumghai** [comment]
Having examined the existing **R&D_node_icon_ionpropulsion** and **R&D_node_icon_nuclearpropulsion**, here are my thoughts on how I would approach this request:
- The essence of an icon is that it is easily recognisable with as few graphical elements as possible, which the existing stock icons are.
- When extending a set of existing icons, continuity aids rapid recognition.
- R&D Tech Node icons should avoid having anything close to the top left corner (if I recall correctly), as that is where the little numbered pip with representing the number of parts that can be unlocked are located.
- The new nodes, tentatively dubbed **Advanced Ion Propulsion (R&D_node_icon_advionpropulsion)** and **Advanced Nuclear Propulsion (R&D_node_icon_advnuclearpropulsion)**, could probably be distinguished from the originals by either having a letter **A** or a Roman Numeral **II** in the top-right corner (I quite like the latter myself).

Howzat?

**Comment by ChrisViral** [comment]
That could work. Alternatively, they could simply have an the same "base" design but with an added element.

I trust you on this one though, as usual. Do what you think would fit best :)

**Comment by sumghai** [comment]
Okies, got the icons ready to be committed. 

Could you please add me as a contributor? Thanks :)

**Comment by ChrisViral** [comment]
There you go, all done.

**Comment by sumghai** [comment]
Okay, icons should be on their way now.

Note the folder structure - I'm tentatively basing it on what SQUAD has done, but feel free to alter it if desired.

**Comment by ChrisViral** [comment]
After taking a look at GameData/Resources/ReadMeTechTreeIcons.txt:

> ---
> 
> Note on all icons::::::::::::::::::::::::::::::::::::::::::::
> 
> All icons contained in the 'RDSimpleIcons' folder are automatically loaded into the game and available to be placed on any custom tech tree node. 
> 
> All icons are supposed to be 64x64 in png format. Icons will be named after the myIcon.png template. In this case the name of the icon would be 'myIcon' and can be loaded by script with 'RDController.Instance.GetIcon("myIcon");'
> 
> Make sure to not use the '_' char or any other 'weird' chars in your icon names. 

I'll be renaming the folder structure and icon names, meanwhile, may you resize the icons to 64x64?

**Comment by ChrisViral** [comment]
Okay so.... further testing revealed that Squad is fucking stupid. The loading folders for _all_ icons are strongly typed to Squad/PartList/Icons, Squad/PartList/SimpleIcons, and Squad/Resources/RDSimpleIcons. I am _not_ writing a plugin to go across this shitty brainfart, so basically a Squad subfolder wil have to do. I've had enough of their BS.

**Comment by ChrisViral** [comment]
Alright, new folder structure/name is up. I scaled up the icons but they lost resolution, so if you would please rerender them at 64x64, that would be great. Looks very nice otherwise :)

**Comment by ChrisViral** [comment]
All tweaks are complete, awaiting only correctly scaled icons for release :)

**Comment by sumghai** [comment]
That's odd - in my copy of KSP 1.0.2*, the original source icons I found for R&D_node_icon_ionpropulsion and R&D_node_icon_nuclearpropulsion were 32 x 32px.

I'll have another look tonight, to see if I can find the 64 x 64px versions of the originals.

*I may be unable to run the game on my laptop, but I can still poke through files.

**Comment by ChrisViral** [comment]
@sumghai those icons are for the editor part filters. The actual icons are hidden in the assets files.

**Comment by sumghai** [comment]
Darn.

There are some tech node icons on the official KSP wiki, but they're actually 60 x 60 px, and have the green gradient background.

I'll have to see if I can extract the originals from the assets files...

**Comment by ChrisViral** [comment]
I'm actually working on it right now.

**Comment by ChrisViral** [comment]
And [here](http://www.mediafire.com/download/lqs2rvv213jew4i/RDIconsLarge.zip) we go. The original files. Had to convert them from .dds to .png after extracting them, but they're the right size and look good to me :) Just work off those I guess!

**Comment by sumghai** [comment]
Perfect - expect the final versions tonight :)

**Comment by sumghai** [comment]
Improved icons are now up (c6e5a1b) - hopefully these work better.

**Comment by ChrisViral** [comment]
Looks all good to me, thank you very much once more!

**Comment by sumghai** [comment]
No worries :)

Addendum: I've put in [a request to remove the hardcoded paths to Squad subfolders for tech tree icons](http://forum.kerbalspaceprogram.com/threads/122918-Tech-Tree-Icon-Modding-Please-remove-hardcoded-paths-to-Squad-folders), although it's doubtful the devs will see it.
